### ISSUE TITLE
【求助】这个要怎么用，在项目里装了报错了但是没看到出发了插件

### ISSUE THREAD

**Issue by mengluo04** [nonebot/plugin-sentry#7]
sentry后台也没收到数据，nb项目的控制台也没看到进入了插件

**Comment by mengluo04** [comment]
> 你是否在启动日志中看到sentry插件被加载成功？如果加载成功了是否有看到`Sentry DSN not provided!`字样？如果没有的话应该是正常启动了，在出现报错的时候sentry会收到日志

从日志信息中可知加载成功
![image](https://github.com/nonebot/plugin-sentry/assets/32565940/eb872de5-b5ed-4288-bbbf-57f150eb760b)
.env.prod文件添加了SENTRY_DSN=https://xxxxx@xxxxx.ingest.us.sentry.io/xxxxx
sentry后台没看到任何数据
![image](https://github.com/nonebot/plugin-sentry/assets/32565940/84dd323f-feb2-48f2-a487-683e46cecd0e)

**Comment by yanyongyu** [comment]
只有在出现error的时候sentry才会出现issue

**Comment by mengluo04** [comment]
> 只有在出现error的时候sentry才会出现issue

搜了下说可以监听error，exception，这个错是exception抛出来的，但是没有监听到
![image](https://github.com/nonebot/plugin-sentry/assets/32565940/427cd2aa-59e6-40dc-b877-c33d3e439217)

**Comment by yanyongyu** [comment]
你把exception捕获了通过info等级记录肯定不会监听啊，正确做法应该是 `logger.opt(exception=True).error("Can not xxx")`

**Comment by mengluo04** [comment]
> 你把exception捕获了通过info等级记录肯定不会监听啊，正确做法应该是 `logger.opt(exception=True).error("Can not xxx")`

好的，因为是开源项目，所以我也不太懂这个，Python知识不太够用
